// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace WC.DataAccess.Models;

public partial class CountryDetail
{
    [Key]
    public int Id { get; set; }

    public string CountryCode { get; set; }

    public string CountryName { get; set; }

    public string CountryRegion { get; set; }

    public string CountrySubregion { get; set; }

    public string FlagUrl { get; set; }
}