// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace WC.DataAccess.Models;

public partial class GeoLocation
{
    [Key]
    public int Id { get; set; }

    public string StartIp { get; set; }

    public string EndIp { get; set; }

    public string CountryCode { get; set; }
}