// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WC.DataAccess.Models;

public partial class GeoLocation
{
    public int Id { get; set; }

    public string StartIp { get; set; }

    public int? StartIpnumber { get; set; }

    public string EndIp { get; set; }

    public int? EndIpnumber { get; set; }

    public string CountryCode { get; set; }
}