// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WC.DataAccess.Models;

public partial class Plan
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public string PlanDescription { get; set; }

    public decimal Price { get; set; }

    public int? RequestLimit { get; set; }

    public bool IsActive { get; set; }
}