// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WC.DataAccess.Models;

public partial class Token
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public DateTime ValidUntil { get; set; }

    public string TokenValue { get; set; }
}