// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WC.DataAccess.Models;

public partial class UserPlan
{
    public int UserPlanId { get; set; }

    public int UserId { get; set; }

    public int PlanId { get; set; }

    public DateTime PlanStart { get; set; }

    public DateTime PlanEnd { get; set; }

    public bool IsActive { get; set; }
}