// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WC.DataAccess.Models;

public partial class WhichCountryContext : DbContext
{
    public WhichCountryContext(DbContextOptions<WhichCountryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CountryDetail> CountryDetails { get; set; }

    public virtual DbSet<GeoLocation> GeoLocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CountryDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CountryD__3214EC274E20E52B");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryCode)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CountryName)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.CountryRegion)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.CountrySubregion)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.FlagUrl)
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasColumnName("FlagURL");
        });

        modelBuilder.Entity<GeoLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GeoLocat__3214EC2717974A8F");

            entity.ToTable("GeoLocation");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryCode)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.EndIp)
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasColumnName("EndIP");
            entity.Property(e => e.StartIp)
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasColumnName("StartIP");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}